// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzBPlvljBPlMylJNIjsEhEHq_1FenlIRA',
    appId: '1:117406445608:web:cdadd2e21c4c70941a851d',
    messagingSenderId: '117406445608',
    projectId: 'roomly-58cf3',
    authDomain: 'roomly-58cf3.firebaseapp.com',
    storageBucket: 'roomly-58cf3.firebasestorage.app',
    measurementId: 'G-SHRN582P9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGy07_EGGI6qUgJAG0DlZrNswgu4iyLlM',
    appId: '1:117406445608:android:1df0f7d8b8cebfb61a851d',
    messagingSenderId: '117406445608',
    projectId: 'roomly-58cf3',
    storageBucket: 'roomly-58cf3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuza9kBYQlYQaxfyfbW0zzEre8LgJFhio',
    appId: '1:117406445608:ios:08333acf8c0771d31a851d',
    messagingSenderId: '117406445608',
    projectId: 'roomly-58cf3',
    storageBucket: 'roomly-58cf3.firebasestorage.app',
    iosBundleId: 'com.roomly',
  );
}
