// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXG40PfozjIOU06QIVzrrdEudCqFMA80',
    appId: '1:492758182833:web:8db89cea16e2ac3f836b90',
    messagingSenderId: '492758182833',
    projectId: 'voice-rooms-b001f',
    authDomain: 'voice-rooms-b001f.firebaseapp.com',
    storageBucket: 'voice-rooms-b001f.firebasestorage.app',
    measurementId: 'G-73GSCJJGQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBhnB9AYdDwAL9HTHOXU9mFas_oB4dZBo',
    appId: '1:492758182833:android:585d53c0fa230228836b90',
    messagingSenderId: '492758182833',
    projectId: 'voice-rooms-b001f',
    storageBucket: 'voice-rooms-b001f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7MCeQRUkzscv7No_q16b_SIznIdfE8bU',
    appId: '1:492758182833:ios:9e72b24ee3dfd935836b90',
    messagingSenderId: '492758182833',
    projectId: 'voice-rooms-b001f',
    storageBucket: 'voice-rooms-b001f.firebasestorage.app',
    iosBundleId: 'com.voiceRooms.voiceRooms',
  );
}
